spring.datasource.url=jdbc:mysql://lifewood-backend-parsacalajane-4d30.d.aivencloud.com:14602/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_NEUJmZJg5-I9Esba5SG


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lukestanleyc@gmail.com
spring.mail.password=dxll bqsu hrvj zyea
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Optional: set default encoding
spring.mail.default-encoding=UTF-8